# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python in Chemistry
author: The Python in Chemistry Community 
# logo: ./logo/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
only_build_toc_files: true
execute:
  execute_notebooks: force

launch_buttons:
  notebook_interface: classic
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://pythoninchemistry.org  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ./logo/favicon.ico
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      TeX:
        packages:
        - cancel
    html_theme_options: 
      logo:
        image_light: ./logo/logo-light.png
        image_dark: ./logo/logo-dark.png
